# Deployment config
baseurl: ""
url: "https://blog.gbplay.io"

# Metadata
title: GBPlay Blog
tagline: Internet-enabled Game Boy multiplayer using original hardware
description: >-
  GBPlay aims to enable Game Boy and Game Boy Color multiplayer over the
  internet using original hardware. It is currently in an early/exploratory
  stage. Stay tuned for more updates as the project progresses.

collections:
  game-protocols:
    output: true

relative_links:
  enabled: true
  collections: true

# Social links
rss: RSS Feed

# Theming
theme: minima
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-relative-links
